services:
  pgvector:
    image: pgvector/pgvector:pg17
    container_name: spring_ai_pgvector
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgvector-data:
